name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
      
    - name: Create env file
      run: |
        touch .env
        echo "${{ secrets.ENV }}" > .env
        cat .env

    - name: PM2 restart
      run: |
        touch key.pem
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
        chmod 400 key.pem
        ssh -i key.pem ${{secrets.USERNAME}}@${{secrets.HOST_DNS}} -p 22 '
        pm2 kill
        cd /home/ec2-user/app-name/
        npm install
        pm2 start npm --name "app-name" -- start -- --port 3000
        '